name: GitHub CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debug:

    runs-on: ubuntu-latest
    container: 
      image: dealii/dealii:latest
      options: --user root


    steps:
    - uses: actions/checkout@v2
    - name: Test debug
      run: |
        rm -rf build_linux_debug
        mkdir build_linux_debug
        cd build_linux_debug
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug
        ninja
        ./lab_test.g

  release:

    runs-on: ubuntu-latest
    container: 
      image: dealii/dealii:latest
      options: --user root

    steps:
    - uses: actions/checkout@v2
    - name: Test release
      run: |
        rm -rf build_linux_release
        mkdir build_linux_release
        cd build_linux_release
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
        ninja
        ./lab_test